### PR TITLE
Create in_array.udo

### PR DESCRIPTION
**Pull request by tgrey1**
UDO searches array for value, returns count found

### CODE REVIEW

**Review by joachimheintz — COMMENTED** [review]
hi kevin -
thanks for your contribution! i like to include this in the repository, but i am asking for some changes.
1. there is a special format of the code in this repository. it is explained in the README.md of this repo. the idea is that you can build and uzse collections of parts (for instance the array udos) or the whole repo, including a santax reference and examples.  can you accept this format and write a .csd file according one of the exosting ones?
2. for the name, i tried to start all array udos with "Arr...". there is a similar udo in the Strays folder which is called "StrayElMem"? would you mind if we call your udo "ArrElMem"?
3. you looked for a k-element in an i-array.  i think we should add also k-element in k-array, and i-element in i-array.  this can simply be done by overloading.
if you want me to, i am happy to give you write access.  in this case, just give me your github user name.
best -
  joachim

**Comment by tgrey1** [comment]
1. Well that's embarrassing, I'll read the readme and work on formatting mine appropriately.  I guess I thought the readme was for using what's there, it didn't dawn on me to read it for contributions too.  Should there be an example for each output type, or is a single example of general usage enough?

2. Honestly, I don't really care what the name is... chances are high I'll leave it named as it is in my own work, because that's what I've known for years (it's builtin in PHP and one or two other languages as "in_array or InArray etc"... and exists as a common include/import in quite a few others).  If you think ArrayElMem is a good/appropriate name, I'm fine with that.

3. I realized after I submitted that krate needle in an irate haystack probably doesn't make sense for most use cases (most of my specific use is during a reinit triggered elsewhere).  I'll write it with a few variable types.  I might be missing something, but wouldn't i and k need separate versions rather than overloading since krate won't run at i-time?  I'll re-think on this some more when I'm actually wearing my coding hat and sitting in front of my laptop ;)

I also don't mind you giving me write access, but I really don't do a whole lot on github, so I don't want to end creating havoc by hitting a wrong button.  I won't mind contributing without it if possible for a while until I don't feel like "Little Bobby Tables" if it's safer...

**Comment by joachimheintz** [comment]
overloading means: write a udo with name Bla and input type ki[], and 
then another udo definition with the same name Bla and input type kk[]. 
then you can use both types (in this case k- or i-array) and csound will 
look for the appropriate definition.  in this case ki[] and kk[] makes 
sense, i think, and for general use we could also add ii[].

it is fine with me when you send me the file, either as pull request or 
privately.  you can stick on your names and i can change it.  just 
wanted to ask you for permission.

**Comment by tgrey1** [comment]
I'm going to close this one and open a new push request soon.  I ran into some issues that I thought were problems with the opcode, but ended up being related to some string issues in 6.07.  I have issues with a lot of my cabbage work running in 6.09, so I was waiting to upgrade until I try 6.10 and hopefully they're resolved.

And yes, you taught me about overloading a year or so ago when dealing with setting multiple channels at once, I use it all the time now.  I was overthinking it, trying to figure a way to share the main bulk of the code and just having different input type UDOs all call one with the core functionality.  Not worth the complexity of trying here really.

Anyways, a dual purpose test/example is written and variables are formatted more in line with your style.  I'll submit it as ArrElMem in the main .udo file, and submit a .csd with the example... with each overloaded version tested in the one file but by a clear individual test.  Going to send to you directly for feedback first.

Thanks!

**Pull request closed without merging**
