### PR TITLE
Added variable parameter count

### PR DESCRIPTION
**Pull request by hlolli**
Now it doesn't matter if instrument is assigned to more or fewer parameters during performance. Also fixed a bug.

### CODE REVIEW

**Comment by joachimheintz** [comment]
thanks.  are you also able to use the conventions of this collection? 
they are described in the readme.md.  the reason is that
1) the whole collection is checked automatically by the python script
2) dependencies are organized (important in your case)
3) an include file is generated automatically

**Comment by hlolli** [comment]
I will try to do this on sunday, didn't know about this python
functionality.

2016-03-11 21:51 GMT+01:00 joachimheintz notifications@github.com:

**Comment by hlolli** [comment]
Sorry for how long time this has taken. I'm bit confused. As I see it, I should create a file live_loop.dep that states all the dependencies (mostly string arrays) but they are included in another directory. Does this make a difference on how I should structure a live_loop.dep textfile?

**Comment by joachimheintz** [comment]
i think this should work.  you just need to specify the correct name.

**Comment by hlolli** [comment]
Ok, can you see how this looks now, I believe I changed some straylen2 from the original. Why I did it, I forgot. But all the dependencies from other udos on the csudo I believe were listed. But let me know if this needs to be different.

**Comment by joachimheintz** [comment]
this repository actually works a bit different.  i try to explain.

what the repo needs from your side is this (see, for instance, 
strays/StrayElMem):
1) a .csd which includes:
   a) at the top a documentation in /**\* ... ***/
       you did this; it might be useful to follow the standard pattern 
of the manual.
   b) a working example.
2) a .setdep file like the one you find in strays/strays.setdep

note that the .udo file _is generated_ automatically from these two file 
inputs.  you do _not_ write it by hand.

so: could you push 1) and 2) to the repo?  or did i miss anything?  i 
only see events/live_loop.udo.

**Comment by hlolli** [comment]
I may need to look better into including a working example, but the last
thing I did was adding live_loop.setdep textfile.... let me investigate.

2016-03-23 22:16 GMT+01:00 joachimheintz notifications@github.com:

**Comment by hlolli** [comment]
https://github.com/csudo/csudo/pull/2/commits/d036e16e3090768f54453adf6b4dd67f5b070636 Here's the file live_loop.setdep, I will add a working example. So I should change live_loop.udo into live_loop.csd as well?

**Comment by joachimheintz** [comment]
ah ok that's what i missed.  but how can i merge it?  i only see:
"hlolli wants to merge 3 commits into csudo:master from hlolli:master"

but i see nothing to merge it, although i am logged in.

**Comment by hlolli** [comment]
2 of the commits are (important) changes to live_loop.udo and 1 commit is adding a new file. It's called merge I guess even tough this file is being created for the first time.

**Comment by joachimheintz** [comment]
a ok - found it.

**Comment by joachimheintz** [comment]
the .setdep should be called "events.setdep", because it is for all the udos which are in this folder.  i changed this, can you pull?

looking at your code, it looks like there are a lot more dependencies.  should all get an own .csd ...

also, i am wondering whether you really need StrayLen2.  it looks like it is only the k-rate version of StrayLen.  so you can overload it (i think we already tried it): 2 definitions using the same name, and csound will know from the context which one to use.

**Comment by hlolli** [comment]
Let me do a research if I can just drop StrayLen2, I think this came as a result of endless debugging efforts. As for small helper udos like parametercount etc. You think I should make a .csd for those udo's? I will pull from origin to my fork with the changes you made as well.

**Comment by joachimheintz** [comment]
yes, i'd say drop StrayLen2.  simply define StrayLen for k.

i did ... can you try the attached version?  it is sometimes a bit 
tricky because you have to ensure that the string is updated at k-rate. 
  but seems to work.

and yes, please provide a .csd for all the udo's you use.  i will give 
you direct access to the repo; this makes it easier for both of us.

**Pull request merged**
